{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: lima-camera-simulator
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - sip >=4.19.20* # API v12.7
    - lima-core
  build:
    - cmake
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('sip', min_pin='x.x.x', max_pin='x') }}
    - {{ pin_compatible('lima-core', max_pin='x.x') }}

test:
  imports:
    - Lima.Simulator

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
