{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: lima-camera-simulator
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - git
    - cmake
    - {{ compiler('cxx') }}
    - lima-core
  host:
    - python {{ python }}
    - numpy
    - sip 4.18*           #For the SIP generator
  run:
    - python {{ python }}
    - sip 4.18*           #For the SIP module
    - lima-core

test:
  requires:
    - cmake
  import:
    - Lima.Simulator
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
